import { Urbanist, Inter, Poppins , Anek_Malayalam  } from "next/font/google";
import "./globals.css";



const urban = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const anekMalayalam = Anek_Malayalam({
  variable: "--font-anek-malayalam",
  subsets: ["malayalam"],
  weight: ["100","200","300","400","500","600","700","800"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${urban.variable} ${inter.variable} ${poppins.variable} ${anekMalayalam.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
